#!/bin/bash

echo "📋 GUÍA DE SUBIDA A GITHUB"
echo "=========================="
echo ""
echo "🎯 Repositorio: https://github.com/saltbalente/chat-whatsapp-backend"
echo ""
echo "📦 Archivos listos para subir:"
echo "   - 23 archivos en total"
echo "   - API REST completa"
echo "   - Scraper Python/Selenium"
echo "   - Cliente iOS Swift"
echo "   - Documentación completa"
echo ""
echo "⚡ COMANDOS PARA EJECUTAR:"
echo ""
echo "1️⃣  Hacer commit:"
echo "   git commit -F COMMIT_MESSAGE.txt"
echo ""
echo "2️⃣  Subir a GitHub:"
echo "   git push -u origin main"
echo ""
echo "💡 O ejecuta estos comandos en una sola línea:"
echo ""
echo "git commit -F COMMIT_MESSAGE.txt && git push -u origin main"
echo ""
echo "=========================="
echo ""
echo "🔐 IMPORTANTE:"
echo "Si es la primera vez, Git te pedirá autenticación."
echo "Usa tu token de GitHub (no la contraseña)."
echo ""
echo "🌐 DESPUÉS DE SUBIR:"
echo ""
echo "1. Ve a: https://github.com/saltbalente/chat-whatsapp-backend"
echo "2. Verifica que todos los archivos estén ahí"
echo "3. Lee el README.md para instrucciones"
echo "4. Despliega en Render siguiendo DEPLOY_RENDER.md"
echo ""
echo "✅ ¿Listo para subir? Ejecuta:"
echo ""
echo "git commit -F COMMIT_MESSAGE.txt && git push -u origin main"
echo ""
